# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb1ee742ae8e1ee6e299d270e11bbd6dde80d8650518d43d525df4d10677dec1c551986969a0c27cf960d98430230a4f4fac15450239e237d16ece549d2e15b

test:
  secret_key_base: 511bc5921fa2c9e20379b02c4e996a8b13af645fc46da25e8ee47a8d8d129c0149071424f869188767c3091ed3e60d954d1892cc7b485e9f3321ff43be8df34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
